# frozen_string_literal: true
ruby "2.6.6"

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "aws_pub_sub", github: "baccigalupi/aws_pub_sub"
gem "pg", "~> 1.2"
gem "sequel", "~> 5.31"

group :development, :test do
  gem "dotenv", "~> 2.7"
  gem "foreman", "~> 0.87.1"
  gem "standard", "~> 0.2.3"
  gem "rspec", "~> 3.9"
end
